### PR TITLE
Adding Vince and Updating Citation Info

### PR DESCRIPTION
**Pull request by gwaygenomics**
@vincerubinetti - can you add yourself and update the citation in https://greenelab.github.io/BioBombe/?

This will address #182

### CODE REVIEW

**Comment by gwaygenomics** [comment]
@vincerubinetti - I believe I was able to find the necessary change. Not sure how to propagate it to the actual website though

**Comment by cgreene** [comment]
I'm pretty sure with github pages this will show up as live in ~5 mins

**Comment by vincerubinetti** [comment]
Sorry I didnt see this notification in time. What you did should be fine and propagate to the gh-pages site soon.

**Comment by gwaygenomics** [comment]
it's live!

**Pull request merged**
